# Generated by Django 3.1.3 on 2021-06-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_remove_notice_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단고정'),
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
